/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 tribute.glb -t, -i, -T, s 
Files: tribute.glb [9MB] > tribute-transformed.glb [1.01MB] (89%)
*/

import * as THREE from "three";
import tributePath from "./flower.glb?url";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    ribbon001: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    White_Flower: THREE.Mesh;
    Cube003: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;

    ribbon: THREE.MeshStandardMaterial;
    ["Flower-tulip  stalk.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    ["White Flower"]: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
  };
};
type TributeProps = {
  onTributeClick?: () => void;
} & JSX.IntrinsicElements["group"];

export default function Tribute({ onTributeClick, ...other }: TributeProps) {
  const { nodes, materials } = useGLTF(tributePath) as GLTFResult;
  return (
    <group {...other} dispose={null}>
      <group
        position={[-0.004, 1.498, -0.196]}
        rotation={[2.74, 0.002, -3.141]}
        scale={[1.092, 1.522, 0.152]}
        onClick={onTributeClick}
      >
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials.PaletteMaterial001}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials.PaletteMaterial002}
          castShadow
          receiveShadow
        />
      </group>
      <mesh // 리본
        geometry={nodes.ribbon001.geometry}
        material={materials.ribbon}
        position={[0.751, 2.661, -0.513]}
        rotation={[1.179, 0, 0]}
        castShadow
        receiveShadow
      />
      <group //꽃
        position={[-1.186, -0.028, 1.042]}
        rotation={[0, -0.002, 0]}
        scale={8.398}
      >
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials["Flower-tulip  stalk.001"]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials.PaletteMaterial002}
          castShadow
          receiveShadow
        />
      </group>
      <mesh
        visible={false}
        geometry={nodes.White_Flower.geometry}
        material={materials["White Flower"]}
        position={[-1.264, 0.227, 1.037]}
        rotation={[0, -0.002, 0]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.PaletteMaterial003}
        position={[1.445, 0.04, 0.636]}
        rotation={[0, -0.002, 0]}
        scale={4.018}
        castShadow
        receiveShadow
      />
    </group>
  );
}
